### ISSUE TITLE
confused about the embedding

### ISSUE THREAD

**Issue by cailurus** [zonetrooper32/VDCNN#13]
great work dude, sorry for my rude, I was just confused about the embedding layer in [code](https://github.com/zonetrooper32/VDCNN/blob/keras_version/vdcnn.py#L69)

for my knowledge, it usually be `Embedding(input_dim=$vocab_size, output_dim=$embedded_size, input_length=$input_size)`

**Comment by zhongzhh8** [comment]
I am confused too.Do you understand it now?

**Comment by mmpang** [comment]
I'm also confused about the argument of Embedding. Could @zonetrooper32 please explain why assign input_length to input_dim? Thanks a lot !

**Comment by cjiang2** [comment]
> I'm also confused about the argument of Embedding. Could @zonetrooper32 please explain why assign input_length to input_dim? Thanks a lot !

Correct embedding implementation is updated in main branch, along with Tensorflow 2 support.
