### ISSUE TITLE
Training fails

### ISSUE THREAD

**Issue by zjfheart** [zonetrooper32/VDCNN#15]
Hi, 

I run your code on ag_news, but every time encounter a training failure. (test acc is 25%). 

Look like the way you recovered has some issues. any ideas about this?

**Comment by WindHunter-Yang** [comment]
me, too  How to solve this problem

**Comment by Valenser** [comment]
have the same problem. any help? :)

**Comment by zjfheart** [comment]
Pls, refer to this paper <https://arxiv.org/abs/1902.10887>. Make your h smaller. This can helps with training.

**Comment by zhongzhh8** [comment]
> have the same problem. any help? :)

how did you solve this problem finally?I need your help

**Comment by zjfheart** [comment]
![Screen Shot 2019-05-09 at 11 51 27](https://user-images.githubusercontent.com/10344081/57426169-c8017680-7250-11e9-9e40-4d1b5e7abcfd.png)
For AG-NEWS dataset, this is my results. 
25 acc signify training failure.

**Comment by zhongzhh8** [comment]
> Pls, refer to this paper https://arxiv.org/abs/1902.10887. Make your h smaller. This can helps with training.
I have the error of a constantly 25 acc in AF_NEWS and do not know how to solve this problem. Do you mean that you change the parameter lr=0.1 in "optimizer=SGD(lr=0.01, momentum=0.9)"? I try it but it does not work. Please tell me how you solved this problem in detail. I need your help.

**Comment by zhongzhh8** [comment]
@zjfheart 
thank you very much. In AG_NEWS and deep 9, I try to set lr=0.001,and it works! After 1 epoch it has raised to 80 acc . Your answer reminds me of the training step. Thank you .
