### ISSUE TITLE
Minor Bug

### ISSUE THREAD

**Issue by atnikos** [zonetrooper32/VDCNN#5]
ag news dataset test doesnt reach 1024 threshold but if you run the code for yahoo answers which reaches beyond 102 you'll get an error because you substitute character before checking for reaching 1024.The condition of reaching max sequence length should be on top of all!

**Comment by cjiang2** [comment]
Thank you for pointing this out. I'll address this issue along with the updates for optional shortcut, which I'll finish testing soon. :)
