### ISSUE TITLE
load_csv_file() only loads description field

### ISSUE THREAD

**Issue by GateStainer** [zonetrooper32/VDCNN#7]
text = row['fields'][-1].lower()

This code in function load_csv_file() doesn't load title part of the text. However, I think in the paper, both title and description part of the text are put into training.

**Comment by cjiang2** [comment]
Hi, sorry for the late reply. 
This is the part which I am not sure. Although the code can be easily modified to encode both title and description. 
I'll put a switch to choose to load title during the next update, no worries.
