### ISSUE TITLE
Please state which license (Apache?) 

### ISSUE THREAD

**Issue by jimidle** [zonetrooper32/VDCNN#9]
Thanks for doing this work - it saves me from following the same paper and reproducing it myself. At least it will if you are willing to give this an Apache license, as I need to implement a commercial version of this and cannot without a license that allows me to. 

Are you willing to issue under the Apache license and add that to the source code and MD?

**Comment by cjiang2** [comment]
Sorry for the late reply.
License issued. Although there are still bugs in the codes but I'll be fixing them recently.
Also good luck with your commercial product.
